### PR TITLE
fix version num of conda package

### PR DESCRIPTION
**Pull request by jenshnielsen**
Trying to fix https://github.com/QCoDeS/Qcodes/discussions/4234

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]
seems to be a weird error with conda builds, right? because on pypi everything is correct

**Comment by jenshnielsen** [comment]
@astafan8 Yes, I think what happens is that conda downloads the sdist and then conda calling pip overwrites the PKG-INFO file (which already contained the right version info)

**Comment by jenshnielsen** [comment]
@conda-forge-admin please rerender

**Comment by jenshnielsen** [comment]
output from pip config list

```
source tree in: /home/conda/feedstock_root/build_artifacts/qcodes_1654613283818/work
export PREFIX=/home/conda/feedstock_root/build_artifacts/qcodes_1654613283818/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/qcodes_1654613283818/_build_env
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/qcodes_1654613283818/work
:env:.cache-dir='/home/conda/feedstock_root/build_artifacts/qcodes_1654613283818/pip_cache'
:env:.ignore-installed='True'
:env:.no-build-isolation='False'
:env:.no-dependencies='True'
:env:.no-index='True'

```

**Pull request merged**
